In [7]:
import pandas as pd

In [5]:
df = pd.read_csv("../data/raw/ar_properties.csv")

In [6]:
df.head()

,id,ad_type,start_date,end_date,created_on,lat,lon,l1,l2,l3,...,bathrooms,surface_total,surface_covered,price,currency,price_period,title,description,property_type,operation_type
0,7LoZFkSIPOTox0r32ck42Q==,Propiedad,2019-09-15,2019-10-26,2019-09-15,-26.815439,-65.312393,Argentina,Tucumán,Yerba Buena,...,NaN,NaN,NaN,NaN,NaN,Mensual,Terreno - Yerba Buena,Accesos pavimentados.<br>Red subterránea de ag...,Lote,Venta
1,QsZD4OxZInNd5po5LQDRmg==,Propiedad,2019-09-15,9999-12-31,2019-09-15,-26.839469,-65.212790,Argentina,Tucumán,NaN,...,1.0,55.0,41.0,NaN,NaN,Mensual,Departamento - Capital,Detalles constructivos:<br><br>Pisos de porcel...,Departamento,Venta
2,qDtysoUgbnHLp0W9We+8fg==,Propiedad,2019-09-15,2019-09-25,2019-09-15,-31.424820,-64.181225,Argentina,Córdoba,Córdoba,...,1.0,45.0,45.0,NaN,NaN,Mensual,1 DORMITORIO | San Lorenzo al 400,Alquiler temporario de Departamento 1 DORMITOR...,Departamento,Alquiler temporal
3,olj51zV0HFurmaZ78U0ssg==,Propiedad,2019-09-15,2019-09-25,2019-09-15,-31.421242,-64.190798,Argentina,Córdoba,Córdoba,...,1.0,48.0,48.0,NaN,NaN,Mensual,1 DORMITORIO | M. T. de Alvear al 500,Alquiler temporario de Departamento 1 DORMITOR...,Departamento,Alquiler temporal
4,OcS1SAA5oAzjZ3Mzg3XHyg==,Propiedad,2019-09-15,2019-09-25,2019-09-15,-31.426064,-64.180042,Argentina,Córdoba,Córdoba,...,1.0,45.0,45.0,NaN,NaN,Mensual,1 DORMITORIO | Av. Poeta Lugones al 200,Alquiler temporario de Departamento 1 DORMITOR...,Departamento,Alquiler temporal

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 25 columns):
 #   Column           Non-Null Count    Dtype
---  ------           --------------    -----
 0   id               1000000 non-null  str
 1   ad_type          1000000 non-null  str
 2   start_date       1000000 non-null  str
 3   end_date         1000000 non-null  str
 4   created_on       1000000 non-null  str
 5   lat              850472 non-null   float64
 6   lon              849456 non-null   float64
 7   l1               1000000 non-null  str
 8   l2               1000000 non-null  str
 9   l3               944673 non-null   str
 10  l4               249223 non-null   str
 11  l5               4616 non-null     str
 12  l6               0 non-null        float64
 13  rooms            531101 non-null   float64
 14  bedrooms         368640 non-null   float64
 15  bathrooms        770378 non-null   float64
 16  surface_total    578777 non-null   float64
 17  surface_covered  549945 non-null   float64
 18  price            951327 non-null   float64
 19  currency         945495 non-null   str
 20  price_period     418899 non-null   str
 21  title            999972 non-null   str
 22  description      999975 non-null   str
 23  property_type    1000000 non-null  str
 24  operation_type   1000000 non-null  str
dtypes: float64(9), str(16)
memory usage: 190.7 MB

In [9]:
df.shape

(1000000, 25)

In [10]:
df.columns

Index(['id', 'ad_type', 'start_date', 'end_date', 'created_on', 'lat', 'lon',
       'l1', 'l2', 'l3', 'l4', 'l5', 'l6', 'rooms', 'bedrooms', 'bathrooms',
       'surface_total', 'surface_covered', 'price', 'currency', 'price_period',
       'title', 'description', 'property_type', 'operation_type'],
      dtype='str')

In [11]:
df["property_type"].unique()

<StringArray>
[           'Lote',    'Departamento',              'PH',            'Casa',
         'Oficina',            'Otro', 'Local comercial',         'Cochera',
        'Depósito',   'Casa de campo']
Length: 10, dtype: str

In [12]:
df["property_type"].value_counts()

property_type
Departamento       419519
Casa               192570
Otro               173047
Lote                91969
Local comercial     38371
PH                  36784
Oficina             27503
Cochera             10290
Depósito             8143
Casa de campo        1804
Name: count, dtype: int64

In [13]:
df["operation_type"].value_counts()

operation_type
Venta                745268
Alquiler             221646
Alquiler temporal     33086
Name: count, dtype: int64

In [14]:
df["l1"].value_counts()

l1
Argentina         976083
Uruguay            23146
Estados Unidos       727
Brasil                44
Name: count, dtype: int64

In [15]:
df["l2"].value_counts()

l2
Capital Federal                 288661
Bs.As. G.B.A. Zona Norte        150293
Buenos Aires Costa Atlántica    143963
Santa Fe                         92080
Bs.As. G.B.A. Zona Sur           87485
Bs.As. G.B.A. Zona Oeste         71373
Córdoba                          60753
Buenos Aires Interior            21369
Maldonado                        12319
Mendoza                          12032
Neuquén                          11471
Montevideo                        8960
Río Negro                         6902
Entre Ríos                        5483
Tucumán                           5404
Misiones                          5188
Salta                             3571
San Luis                          2194
Chaco                             1280
La Pampa                          1218
San Juan                          1206
Chubut                            1144
Colonia                            989
Corrientes                         988
Canelones                          696
Jujuy                              631
Tierra Del Fuego                   457
Florida                            340
Catamarca                          297
Santa Cruz                         292
Rocha                              182
Santiago Del Estero                146
Maryland                           137
La Rioja                           121
Michigan                           116
Miami                               99
Formosa                             81
Pennsylvania                        33
Santa Catarina                      30
Rio de Janeiro                      13
New York                             2
São Paulo                            1
Name: count, dtype: int64

In [16]:
df["l3"].value_counts()

l3
Mar del Plata         123726
Rosario                69899
Tigre                  44710
Palermo                39672
La Plata               35483
                       ...
Paso de los Libres         1
Alpasinche                 1
Las Lomitas                1
Mina Pan de Azúcar         1
Colonia Carrasco           1
Name: count, Length: 1267, dtype: int64

In [17]:
df["l4"].value_counts()

l4
Nordelta            18873
La Plata             9862
Ramos Mejía          7255
Castelar             6535
Olivos               5457
                    ...
Las Beatrices           1
Norumbega               1
La Porteña              1
Mayor Buratovich        1
Pavón                   1
Name: count, Length: 982, dtype: int64

In [18]:
df["l5"].value_counts()

l5
BarrioPortezuelo                734
Barrio El Golf                  721
Barrio Los Alisos               389
Barrio Los Lagos                368
Barrio Los Castores             265
Barrio Los Sauces               243
Barrio Los Tilos                212
Barrio El Yacht                 205
Barrio Barrancas del Lago       204
Islas del Canal                 192
Barrio Lagos del Golf 2         183
Barrio Las Glorietas            171
Barrio La Alameda               155
Barrio Cabos del Lago           138
Barrio La Isla                  130
Barrio Las Caletas               83
Enyoi                            75
Barrio Lagos del Golf 1          66
QBay Yacht                       36
Barrio Residencial Pacheco 2     35
Barrio Residencial Pacheco 1     11
Name: count, dtype: int64

In [19]:
df["l6"].value_counts()

Series([], Name: count, dtype: int64)

In [20]:
df["currency"].value_counts()

currency
USD    699509
ARS    243595
UYU      2329
PEN        62
Name: count, dtype: int64

In [21]:
df[["start_date", "end_date", "created_on"]].head(10)

   start_date    end_date  created_on
0  2019-09-15  2019-10-26  2019-09-15
1  2019-09-15  9999-12-31  2019-09-15
2  2019-09-15  2019-09-25  2019-09-15
3  2019-09-15  2019-09-25  2019-09-15
4  2019-09-15  2019-09-25  2019-09-15
5  2019-09-15  2019-09-25  2019-09-15
6  2019-09-15  2019-09-25  2019-09-15
7  2019-09-15  2019-09-25  2019-09-15
8  2019-09-15  2019-09-25  2019-09-15
9  2019-09-15  2019-09-25  2019-09-15

In [22]:
df["start_date"].min()

'2019-03-01'

In [23]:
df["start_date"].max()

'2020-03-23'

In [24]:
((df["operation_type"] == "Venta") &
 (df["property_type"] == "Departamento") &
 (df["l2"] == "Capital Federal") &
 (df["currency"] == "USD")).sum()

np.int64(121442)

In [25]:
caba_sales = df[
    (df["operation_type"] == "Venta") &
    (df["property_type"] == "Departamento") &
    (df["l2"] == "Capital Federal") &
    (df["currency"] == "USD")
].copy()

In [26]:
caba_sales.shape

(121442, 25)

In [27]:
caba_sales["id"].nunique()

121442